extends: google
rules:
  indent:
    - 2 # Error
    - tab
  max-len:
    - 0 # Off
  new-cap:
    - 0 # Off
  no-eq-null:
    - 0 # Off
  eqeqeq:
    - 2 # Error
    - allow-null
  require-jsdoc:
    - 0 # Off
  no-trailing-spaces:
    - 2 # Error
    - skipBlankLines: true